In [13]:
import src.data.downloader

print(src.data.downloader.__file__)

/Users/akash/PycharmProjects/POR-Dashboard/src/data/downloader.py

In [14]:
import inspect
from src.data.downloader import download_stock

print(inspect.getsource(download_stock))

def download_stock(ticker, period='5y'):
    data = yf.download(
        ticker,
        period=period,
        auto_adjust=False,
        multi_level_index=False,
        progress=False
    )

    if data.empty:
        return pd.DataFrame()

    data = data.reset_index()

    data = data[
        ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
    ]

    data['Ticker'] = ticker

    data = data[
        ['Ticker', 'Date', 'Open', 'High', 'Low', 'Close', 'Volume']
    ]

    return data

In [15]:
import src.data.downloader

print(src.data.downloader.__file__)

/Users/akash/PycharmProjects/POR-Dashboard/src/data/downloader.py

In [16]:
import src.data.downloader

print(src.data.downloader.__file__)

/Users/akash/PycharmProjects/POR-Dashboard/src/data/downloader.py

In [17]:
import importlib
import src.data.downloader

importlib.reload(src.data.downloader)

In [18]:
from src.data.downloader import download_stock

test = download_stock("360ONE.NS")

test.head()

      Ticker       Date      Open    High         Low       Close  Volume
0  360ONE.NS 2021-09-01  409.9375  415.00  395.000000  400.200012  206156
1  360ONE.NS 2021-09-02  407.5000  412.50  395.512512  400.262512  146008
2  360ONE.NS 2021-09-03  400.5000  401.25  390.262512  395.362488  115372
3  360ONE.NS 2021-09-06  396.2500  404.75  395.500000  400.837494  523692
4  360ONE.NS 2021-09-07  409.5000  409.50  392.587494  397.162506  107104

In [19]:
tickers = ["360ONE.NS", "3MINDIA.NS", "ABB.NS"]

for ticker in tickers:
    data = download_stock(ticker)
    print(ticker, data.shape)

360ONE.NS (1239, 7)
3MINDIA.NS (1238, 7)
ABB.NS (1240, 7)

In [20]:
from src.data.cleaner import clean_stock

cleaned = clean_stock(test)

cleaned.head()

      Ticker       Date      Open    High         Low       Close  Volume
0  360ONE.NS 2021-09-01  409.9375  415.00  395.000000  400.200012  206156
1  360ONE.NS 2021-09-02  407.5000  412.50  395.512512  400.262512  146008
2  360ONE.NS 2021-09-03  400.5000  401.25  390.262512  395.362488  115372
3  360ONE.NS 2021-09-06  396.2500  404.75  395.500000  400.837494  523692
4  360ONE.NS 2021-09-07  409.5000  409.50  392.587494  397.162506  107104

In [21]:
cleaned.shape

(1239, 7)

In [22]:
cleaned.isna().sum()

Ticker    0
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [23]:
test_bad = test.copy()

test_bad.loc[test_bad.index[:100], 'Close'] = None

In [24]:
test_bad['Close'].isna().mean()

np.float64(0.08151735270379339)

In [25]:
cleaned_bad = clean_stock(test_bad)

cleaned_bad.empty

False

In [26]:
data[required_columns].isna().mean()

NameError: name 'required_columns' is not defined

In [27]:
test_good = test.copy()

test_good.loc[test_good.index[:20], 'Close'] = None

cleaned_good = clean_stock(test_good)

cleaned_good['Close'].isna().sum()

np.int64(20)